"""add classification columns to summaries

Revision ID: c99e76ac8c2f
Revises: 9b129ea8e054
Create Date: 2026-10-09 10:18:37.474346

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c99e76ac8c2f"
down_revision: str | Sequence[str] | None = "9b129ea8e054"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summaries", sa.Column("matched_categories", sa.ARRAY(sa.String(length=50)), nullable=False)
    )
    op.add_column("summaries", sa.Column("mentions_price", sa.Boolean(), nullable=False))
    op.add_column("summaries", sa.Column("mentions_israel", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summaries", "mentions_israel")
    op.drop_column("summaries", "mentions_price")
    op.drop_column("summaries", "matched_categories")
    # ### end Alembic commands ###
